version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/autod
      SPRING_DATASOURCE_USERNAME: autod
      SPRING_DATASOURCE_PASSWORD: adm
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: true
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "13555:5432"
    environment:
      POSTGRES_DB: autod
      POSTGRES_USER: autod
      POSTGRES_PASSWORD: adm
